### ISSUE TITLE
anyinputのバグ

### ISSUE THREAD

**Issue by isamu** [isamu/graphai#64]

**Comment by isamu** [comment]
```
version: 0.5
nodes:
  no_tool_calls:
    value: []
  tool_calls:
    value: [1,1]
  reducer:
    agent: "bypassAgent"
    anyInput: true
    isResult: true
    inputs:
      - :no_tool_calls
      - :tool_calls
```

```

{
  "reducer": [
    [],
    [
      1,
      1
    ]
  ]
}
```
